table! {
    registrants (db_identifier) {
        db_identifier -> Unsigned<Bigint>,
        email -> Varchar,
        first_name -> Varchar,
        last_name -> Varchar,
        gender -> Varchar,
        phone -> Bigint,
        school -> Varchar,
        tshirt -> Varchar,
        driving -> Bool,
        reimbursement -> Bool,
        reimbursement_amount -> Nullable<Bigint>,
        reimbursement_desc -> Nullable<Text>,
        reimbursement_strict -> Nullable<Bool>,
        minor -> Bool,
        accommodations -> Nullable<Text>,
        dietary_restrictions -> Nullable<Text>,
        user_identifier -> Bigint,
        country -> Varchar,
        level_of_study -> Varchar,
        age -> Bigint,
        mlh_mailing_list -> Bool,
    }
}
